# BetterMOTD config
# This is all that is needed for a custom MOTD. See the README for optional settings.
colorFormat: "AUTO"

profiles:
  default:
    presets:
      - id: "main"
        motd:
          - "<gradient:#00D431:#00BF4B><bold>BetterMOTD</bold></gradient>"
          - "<gray>Online: <white>%online%</white>/<white>%max%</white> | %version%</gray>"
