name: BetterMOTD
version: 1.0.0
main: bettermotd.BetterMOTDPlugin
api-version: "1.21"
author: DefaultSquad

commands:
  bettermotd:
    description: Manage BetterMOTD
    usage: /bettermotd <reload|profile|preview>
    aliases: [bm]

permissions:
  bettermotd.admin:
    description: Grants all BetterMOTD commands
    default: op
