name: BetterMOTD
version: 1.0.0
main: bettermotd.BetterMOTDPlugin
api-version: "1.21"
author: DefaultSquad

commands:
  bettermotd:
    description: Reload BetterMOTD config
    usage: /bettermotd reload
permissions:
  bettermotd.reload:
    default: op
