name: BetterMOTD
version: 1.0.0
main: bettermotd.BetterMOTDPlugin
api-version: "1.21"
author: DefaultSquad

commands:
  bettermotd:
    description: Manage BetterMOTD
    usage: /bettermotd <reload|test|stats>
    aliases: [bm]

permissions:
  bettermotd.admin:
    description: Grants all BetterMOTD commands
    default: op
  bettermotd.reload:
    description: Reload BetterMOTD config
    default: op
  bettermotd.test:
    description: Test preset selection and MOTD
    default: op
  bettermotd.stats:
    description: View preset pick stats
    default: op
